print("Nama       : Haiva Putri Palmaisyah")
print("NIM        : I0322051")
print("Kota  Asal : Palembang")
print("======================================")
print("Nama saya Haiva dan saya berasal dari Kota Palembang, Provinsi Sumatera Selatan.")
print("Kota Palembang terkenal dengan salah satu kulinernya yaitu Pempek.")
print("Kota Palembang juga memiliki beberapa ikon contohnya Jembatan Ampera yang terbentang di atas Sungai Musi.")
print("Banyak sekali perkembangan yang terjadi di kotaku ini, salah satunya adanya pembangunan LRT.")
print("======================================")
print("Harapan saya sebagai lulusan Teknik Industri kelak adalah bisa menerapkan apa yang saya pelajari selama kuliah dengan bekerja di perusahaan besar, membahagiakan orang tua, dan sukses dunia akhirat.")